# Site settings
title: Katja Rogers
description: 'Postdoctoral researcher in HCI and games'
url: 'ajkt.github.io'
baseurl: ''
# prev: '/jekyll-uno'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Katja Rogers'
  email: katja.s.rogers@gmail.com
  twitter_username: katjesjes
  github_username:  ajkt

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate', 'rack-pratchett']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']

plugins: #formerly: gems:
 - jekyll-font-awesome-sass

font-awesome:
  assets: true
